default_context:
  project_name: 'snoozy'
  project_slug: 'snoozy'
  domain_main: 'snoozy.tech'
  domain_staging: 'stag.snoozy.tech'
  docker_swarm_stack_name_main: 'snoozy-tech'
  docker_swarm_stack_name_staging: 'stag-snoozy-tech'
  secret_key: 'c81baf4b0a07da2fca8ecd941f2fb6478aedcc7a4449a1076f38d1abab544b3a'
  first_superuser: 'admin@snoozy.tech'
  first_superuser_password: 'ef6b106bc61a284bac8c27f5d8bc1c41dca8689d1a270e7b96897cfc8251dc71'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.snoozy.tech", "https://stag.snoozy.tech", "https://snoozy.tech", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@snoozy.tech'
  postgres_password: 'snoozyapptech1908'
  pgadmin_default_user: 'admin@snoozy.tech'
  pgadmin_default_user_password: 'ef6b106bc61a284bac8c27f5d8bc1c41dca8689d1a270e7b96897cfc8251dc71'
  traefik_constraint_tag: 'snoozy.tech'
  traefik_constraint_tag_staging: 'stag.snoozy.tech'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:ef6b106bc61a284bac8c27f5d8bc1c41dca8689d1a270e7b96897cfc8251dc71'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
